#!/bin/bash

#----------------------------------------------------------------------
# Script to get the energies for every input that has been optimized
# by gaussian. In this case, the inputs were generated by the algorithm,
# but it would work for any set of input geometries that have been
# optimized by a Gaussian geometry optimization.
#
#
# The script ... (what does it do?)
#----------------------------------------------------------------------

x=B5V
mkdir SCF_Done
mkdir SCF_Done
mkdir not_finished
for i in {1..15}
do
if [ -d "$i" ]; then
   cd $i
   if [ -f $i-$x.wfn ]
   then
      echo 'wfn exist'
      grep 'Optimized' $i-$x.com.out | cat >> info.txt
      grep 'SCF Done' $i-$x.com.out | tail -1 | cat >> info.txt
      energy=$(grep 'SCF Done' $i-$x.com.out | tail -1 | cut -c26-39)
      echo $i $energy | cat >> ../energies.txt
      echo $i $energy 
      echo ' ' | cat >> info.txt
      grep 'Full point group' $i-$x.com.out | cat >> info.txt
      echo ' ' | cat >> info.txt
      grep -A 40 'Orbital symmetries' $i-$x.com.out | cat >> info.txt
      echo ' ' | cat >> info.txt
      grep -A 20 'Input orientation:' $i-$x.com.out | tail -20 | awk -v f=1 -v t=70 '{for(i=f;i<=t;i++) printf("%s%s",$i,(i==t)?"\n":OFS)}' | awk -v f=11 -v     t=29 '{for(i=1;i<=NF;i++)if(i>=f&&i<=t)continue;else printf("%s%s",$i,(i!=NF    )?OFS:ORS)}' | cat >> info.txt
      unix2dos info.txt
      cd ../
      cp -r $i SCF_Done
      trash -r $i
   elif [ ! -f $i-$x.wfn ]
   then
      echo 'no wfn'
      grep 'SCF Done' $i-$x.com.out | cat > file
      j=$(wc -l < file)
      rm file
      echo i, $i
      echo j, $j
      cd ../
      if [ $j -ge 10 ]
      then
         echo 'good'
         cp -r $i not_finished
         trash -r $i
      elif [ $j -lt 10 ] 
      then
          echo 'not good'
          trash -r $i 
       else 
          echo 'you re doing something wrong'
       fi
    fi 
fi
done



